insert into clientes (id, nombre, apellido, email, create_at, foto) values (1, 'Yoshiko', 'Low', 'ylow0@sohu.com', '2018/05/20', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (2, 'Clarice', 'Donwell', 'cdonwell1@who.int', '2018/10/20', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (3, 'Marti', 'Andrei', 'mandrei2@pcworld.com', '2019/05/14', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (4, 'Ferdinanda', 'Planke', 'fplanke3@webeden.co.uk', '2018/08/09', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (5, 'Lyndy', 'O''Keeffe', 'lokeeffe4@dedecms.com', '2018/08/29', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (6, 'Lavina', 'Drysdell', 'ldrysdell5@istockphoto.com', '2018/07/24', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (7, 'Debby', 'Attlee', 'dattlee6@google.co.jp', '2018/12/09', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (8, 'Temple', 'Ballister', 'tballister7@tiny.cc', '2019/02/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (9, 'Wylie', 'Willox', 'wwillox8@360.cn', '2019/02/21', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (10, 'Harmony', 'Gye', 'hgye9@wufoo.com', '2018/12/31', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (11, 'Kingsley', 'Goodright', 'kgoodrighta@imageshack.us', '2018/07/16', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (12, 'Bastian', 'Proback', 'bprobackb@cbslocal.com', '2018/06/04', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (13, 'Timothee', 'Gooders', 'tgoodersc@surveymonkey.com', '2019/05/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (14, 'Shela', 'Finnick', 'sfinnickd@house.gov', '2018/12/12', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (15, 'Sansone', 'Clowney', 'sclowneye@photobucket.com', '2018/12/26', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (16, 'Ringo', 'Baffin', 'rbaffinf@paypal.com', '2018/09/23', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (17, 'Prince', 'Loddon', 'ploddong@intel.com', '2018/09/12', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (18, 'Raimund', 'Grodden', 'rgroddenh@accuweather.com', '2019/01/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (19, 'Ofilia', 'Stede', 'ostedei@posterous.com', '2019/03/06', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (20, 'Lazaro', 'O''Sesnane', 'losesnanej@barnesandnoble.com', '2019/01/15', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (21, 'Dusty', 'Gurnett', 'dgurnettk@hatena.ne.jp', '2018/12/09', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (22, 'Ruggiero', 'Rozier', 'rrozierl@scientificamerican.com', '2019/02/27', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (23, 'Remus', 'De la croix', 'rdelacroixm@addtoany.com', '2018/11/29', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (24, 'Zaneta', 'Fitzharris', 'zfitzharrisn@goodreads.com', '2018/06/07', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (25, 'Nial', 'Dallemore', 'ndallemoreo@deliciousdays.com', '2019/03/24', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (26, 'Wallis', 'Cantle', 'wcantlep@webmd.com', '2018/07/30', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (27, 'Zaria', 'Valdes', 'zvaldesq@paypal.com', '2018/12/05', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (28, 'Arni', 'Rosbottom', 'arosbottomr@bloglovin.com', '2019/03/11', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (29, 'Willamina', 'Paxforde', 'wpaxfordes@omniture.com', '2018/05/24', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (30, 'Irvin', 'Ellit', 'iellitt@businesswire.com', '2018/06/02', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (31, 'Celeste', 'Quartley', 'cquartleyu@pen.io', '2018/09/19', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (32, 'Vince', 'Wright', 'vwrightv@paypal.com', '2018/11/16', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (33, 'Midge', 'Duckworth', 'mduckworthw@princeton.edu', '2018/06/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (34, 'Dewey', 'Meenan', 'dmeenanx@51.la', '2018/06/21', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (35, 'Margarete', 'Lewzey', 'mlewzeyy@canalblog.com', '2019/03/22', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (36, 'Elnore', 'Durnford', 'edurnfordz@domainmarket.com', '2019/04/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (37, 'Christina', 'Hales', 'chales10@slashdot.org', '2019/03/30', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (38, 'Madelle', 'Huntingford', 'mhuntingford11@eventbrite.com', '2018/06/21', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (39, 'Rosetta', 'Meneghi', 'rmeneghi12@ftc.gov', '2019/05/16', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (40, 'Carey', 'Akenhead', 'cakenhead13@constantcontact.com', '2018/08/26', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (41, 'Robb', 'Pala', 'rpala14@marketwatch.com', '2019/02/10', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (42, 'Rainer', 'Rounsefell', 'rrounsefell15@disqus.com', '2018/12/08', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (43, 'Vally', 'Saterweyte', 'vsaterweyte16@photobucket.com', '2018/12/20', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (44, 'Isadore', 'Birkenhead', 'ibirkenhead17@instagram.com', '2018/05/22', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (45, 'Tadeo', 'Hubbuck', 'thubbuck18@list-manage.com', '2018/07/14', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (46, 'Mable', 'Le Guin', 'mleguin19@tiny.cc', '2018/06/02', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (47, 'Anetta', 'Fulleylove', 'afulleylove1a@nhs.uk', '2019/03/10', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (48, 'Wilmer', 'Arndell', 'warndell1b@g.co', '2019/04/30', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (49, 'Berti', 'Scogings', 'bscogings1c@google.com.br', '2018/09/02', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (50, 'Jeno', 'McGinnis', 'jmcginnis1d@cbc.ca', '2018/11/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (51, 'Jemmie', 'Frankton', 'jfrankton1e@sbwire.com', '2018/10/11', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (52, 'Felicdad', 'Hanson', 'fhanson1f@themeforest.net', '2018/09/10', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (53, 'Truman', 'Vannoort', 'tvannoort1g@tiny.cc', '2019/04/24', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (54, 'Alain', 'Reddy', 'areddy1h@prnewswire.com', '2019/02/14', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (55, 'Stephan', 'Covotti', 'scovotti1i@multiply.com', '2018/12/06', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (56, 'Tito', 'Rigney', 'trigney1j@gravatar.com', '2018/10/23', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (57, 'Lou', 'Munslow', 'lmunslow1k@ed.gov', '2019/04/02', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (58, 'Beltran', 'Topp', 'btopp1l@drupal.org', '2018/07/16', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (59, 'Farrel', 'Sommerling', 'fsommerling1m@nifty.com', '2019/03/20', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (60, 'Florance', 'Lorie', 'florie1n@omniture.com', '2018/08/02', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (61, 'Foss', 'Fallens', 'ffallens1o@quantcast.com', '2019/03/11', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (62, 'Ahmed', 'Howles', 'ahowles1p@berkeley.edu', '2018/06/02', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (63, 'Jessamyn', 'Duthie', 'jduthie1q@theguardian.com', '2018/08/29', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (64, 'Tabor', 'Primmer', 'tprimmer1r@bandcamp.com', '2019/02/17', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (65, 'Winni', 'Gabits', 'wgabits1s@newyorker.com', '2018/07/09', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (66, 'Willy', 'Klimt', 'wklimt1t@constantcontact.com', '2018/09/30', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (67, 'Filide', 'Rubberts', 'frubberts1u@apple.com', '2019/05/02', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (68, 'Elyssa', 'Ottewill', 'eottewill1v@bbc.co.uk', '2019/03/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (69, 'Clemence', 'Atcherley', 'catcherley1w@4shared.com', '2018/08/08', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (70, 'Trude', 'Towne', 'ttowne1x@narod.ru', '2018/05/27', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (71, 'Bellina', 'Bande', 'bbande1y@va.gov', '2018/10/26', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (72, 'Damien', 'Pieche', 'dpieche1z@wp.com', '2019/05/01', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (73, 'Rudolph', 'Sugge', 'rsugge20@nasa.gov', '2019/04/10', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (74, 'Kally', 'enzley', 'kenzley21@auda.org.au', '2018/09/26', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (75, 'Torrin', 'Waldock', 'twaldock22@loc.gov', '2018/12/23', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (76, 'Humfrey', 'Bauer', 'hbauer23@wikispaces.com', '2018/06/24', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (77, 'Pippa', 'Klaggeman', 'pklaggeman24@army.mil', '2018/08/21', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (78, 'Isadore', 'Guillart', 'iguillart25@quantcast.com', '2019/04/15', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (79, 'Teodorico', 'Magnar', 'tmagnar26@cornell.edu', '2018/09/25', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (80, 'Tabbie', 'Rushton', 'trushton27@stumbleupon.com', '2018/10/03', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (81, 'Marlyn', 'Rediers', 'mrediers28@scientificamerican.com', '2019/03/11', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (82, 'Cassey', 'Kenen', 'ckenen29@vimeo.com', '2019/03/04', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (83, 'Pancho', 'Hackforth', 'phackforth2a@artisteer.com', '2018/05/23', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (84, 'Holly', 'Tomlinson', 'htomlinson2b@state.tx.us', '2018/08/29', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (85, 'Torey', 'Govinlock', 'tgovinlock2c@fotki.com', '2018/09/30', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (86, 'Harrietta', 'Docwra', 'hdocwra2d@blogtalkradio.com', '2018/08/19', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (87, 'Ileane', 'Silber', 'isilber2e@fc2.com', '2018/12/29', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (88, 'Monro', 'Gumby', 'mgumby2f@sina.com.cn', '2018/08/25', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (89, 'Ashlan', 'Bent', 'abent2g@imageshack.us', '2018/07/18', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (90, 'Drew', 'Duley', 'dduley2h@miibeian.gov.cn', '2019/02/25', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (91, 'Marilin', 'Churn', 'mchurn2i@people.com.cn', '2018/09/30', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (92, 'Jannelle', 'Beever', 'jbeever2j@ovh.net', '2019/03/15', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (93, 'Durante', 'Waterhous', 'dwaterhous2k@flickr.com', '2018/09/17', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (94, 'Rayshell', 'Bolesworth', 'rbolesworth2l@ed.gov', '2019/03/29', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (95, 'Malva', 'Rankine', 'mrankine2m@hatena.ne.jp', '2018/09/07', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (96, 'Ignacio', 'Orgen', 'iorgen2n@livejournal.com', '2018/09/17', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (97, 'Chryste', 'Fatkin', 'cfatkin2o@nbcnews.com', '2019/02/27', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (98, 'Hali', 'Gyford', 'hgyford2p@php.net', '2018/06/25', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (99, 'Jard', 'Benit', 'jbenit2q@hibu.com', '2019/03/26', '');
insert into clientes (id, nombre, apellido, email, create_at, foto) values (100, 'Byran', 'Innot', 'binnot2r@behance.net', '2018/12/24', '');

insert into productos (nombre, precio, create_at) values ('Tomatoes - Yellow Hot House', 87, '2019/04/14');
insert into productos (nombre, precio, create_at) values ('Compound - Pear', 7, '2018/11/11');
insert into productos (nombre, precio, create_at) values ('Flour Pastry Super Fine', 70, '2019/03/31');
insert into productos (nombre, precio, create_at) values ('Sprouts - Corn', 49, '2018/05/23');
insert into productos (nombre, precio, create_at) values ('Filling - Mince Meat', 72, '2019/03/30');
insert into productos (nombre, precio, create_at) values ('Paper - Brown Paper Mini Cups', 29, '2018/11/16');
insert into productos (nombre, precio, create_at) values ('Onions - Red Pearl', 42, '2018/08/11');
insert into productos (nombre, precio, create_at) values ('Mcguinness - Blue Curacao', 88, '2019/03/12');
insert into productos (nombre, precio, create_at) values ('Ice Cream - Super Sandwich', 18, '2018/08/02');
insert into productos (nombre, precio, create_at) values ('Sauce - Soya, Light', 97, '2019/01/23');
insert into productos (nombre, precio, create_at) values ('Juice - Apple, 1.36l', 34, '2018/05/27');
insert into productos (nombre, precio, create_at) values ('Cocoa Powder - Dutched', 72, '2018/06/01');
insert into productos (nombre, precio, create_at) values ('Greens Mustard', 21, '2019/04/12');
insert into productos (nombre, precio, create_at) values ('Mushroom - Enoki, Fresh', 16, '2018/12/08');
insert into productos (nombre, precio, create_at) values ('Coffee Cup 8oz 5338cd', 22, '2018/07/21');
insert into productos (nombre, precio, create_at) values ('Cranberries - Dry', 33, '2018/05/23');
insert into productos (nombre, precio, create_at) values ('Tea - Mint', 37, '2018/11/23');
insert into productos (nombre, precio, create_at) values ('Lamb - Whole Head Off,nz', 75, '2018/09/22');
insert into productos (nombre, precio, create_at) values ('Ice Cream Bar - Oreo Sandwich', 8, '2018/09/01');
insert into productos (nombre, precio, create_at) values ('The Pop Shoppe - Black Cherry', 61, '2018/12/17');
insert into productos (nombre, precio, create_at) values ('Wanton Wrap', 100, '2018/10/22');
insert into productos (nombre, precio, create_at) values ('Rabbit - Legs', 65, '2018/05/24');
insert into productos (nombre, precio, create_at) values ('Noodles - Cellophane, Thin', 31, '2018/05/27');
insert into productos (nombre, precio, create_at) values ('Brandy - Bar', 28, '2019/04/30');
insert into productos (nombre, precio, create_at) values ('Garbage Bags - Clear', 13, '2018/08/01');
insert into productos (nombre, precio, create_at) values ('Lamb - Whole, Frozen', 90, '2018/07/20');
insert into productos (nombre, precio, create_at) values ('Truffle - Whole Black Peeled', 34, '2019/01/05');
insert into productos (nombre, precio, create_at) values ('Paste - Black Olive', 55, '2019/02/19');
insert into productos (nombre, precio, create_at) values ('Chicken - Wings, Tip Off', 57, '2019/05/16');
insert into productos (nombre, precio, create_at) values ('Yukon Jack', 56, '2018/07/01');
insert into productos (nombre, precio, create_at) values ('Bread - Crusty Italian Poly', 75, '2018/08/15');
insert into productos (nombre, precio, create_at) values ('Beef - Roasted, Cooked', 46, '2018/11/10');
insert into productos (nombre, precio, create_at) values ('Juice - Clamato, 341 Ml', 30, '2018/12/14');
insert into productos (nombre, precio, create_at) values ('Chicken - Diced, Cooked', 31, '2019/05/11');
insert into productos (nombre, precio, create_at) values ('Cheese - Cream Cheese', 99, '2018/11/17');
insert into productos (nombre, precio, create_at) values ('Taro Root', 9, '2018/07/12');
insert into productos (nombre, precio, create_at) values ('Lamb - Leg, Diced', 58, '2018/12/31');
insert into productos (nombre, precio, create_at) values ('Lamb Rack - Ontario', 18, '2019/04/06');
insert into productos (nombre, precio, create_at) values ('Wine - Coteaux Du Tricastin Ac', 11, '2019/02/11');
insert into productos (nombre, precio, create_at) values ('Foil - 4oz Custard Cup', 8, '2019/02/01');
insert into productos (nombre, precio, create_at) values ('Chips Potato Salt Vinegar 43g', 53, '2018/05/31');
insert into productos (nombre, precio, create_at) values ('Tilapia - Fillets', 99, '2019/02/03');
insert into productos (nombre, precio, create_at) values ('Oven Mitt - 13 Inch', 61, '2019/04/12');
insert into productos (nombre, precio, create_at) values ('Wine - Acient Coast Caberne', 13, '2018/06/10');
insert into productos (nombre, precio, create_at) values ('Wine - Rubyport', 23, '2018/09/07');
insert into productos (nombre, precio, create_at) values ('Soup - Canadian Pea, Dry Mix', 58, '2018/09/13');
insert into productos (nombre, precio, create_at) values ('Tequila Rose Cream Liquor', 50, '2019/04/04');
insert into productos (nombre, precio, create_at) values ('Liners - Baking Cups', 96, '2019/05/18');
insert into productos (nombre, precio, create_at) values ('Flour - Corn, Fine', 46, '2018/12/09');
insert into productos (nombre, precio, create_at) values ('Beef - Ground, Extra Lean, Fresh', 6, '2019/04/21');


INSERT INTO facturas (descripcion , observacion ,cliente_id , create_at) VALUES ('Factura equipos de oficina', NULL, 1 , NOW());
INSERT INTO facturas_items (cantidad, factura_id , productos_id) VALUES (1,1,1);
INSERT INTO facturas_items (cantidad, factura_id , productos_id) VALUES (2,1,4);
INSERT INTO facturas_items (cantidad, factura_id , productos_id) VALUES (1,1,5);
INSERT INTO facturas_items (cantidad, factura_id , productos_id) VALUES (1,1,7);

INSERT INTO facturas (descripcion , observacion ,cliente_id , create_at) VALUES ('Factura bicicleta', 'nota pero asi como que super importante', 1 , NOW());
INSERT INTO facturas_items (cantidad, factura_id , productos_id) VALUES (3,2,6);


INSERT INTO users (username,password,enabled) VALUES ('pablo','$2a$10$8So9Hze7citE7h/duQdPw.wYqeNNDo4i4gk91vBPB.cPGWgxfWgv6',1);
INSERT INTO users (username,password,enabled) VALUES ('admin','$2a$10$4YrH2sEySw4ugdgwQLzWh.CQUGloiOt7AzvccFdN8efrJxtLsY9gq',1);
insert into authorities (user_id , authority) values (1 , 'ROLE_USER');
insert into authorities (user_id , authority) values (2 , 'ROLE_USER');
insert into authorities (user_id , authority) values (2 , 'ROLE_ADMIN');